language: csharp
dist: trusty
os: linux
mono: none
dotnet: 2.1
install:
  - dotnet restore
script:
  - dotnet build Cake.Badge/Cake.Badge.csproj
  - dotnet test Cake.Badge.Tests/Cake.Badge.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
before_deploy:
  - sh create_release.sh
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "./Cake.Badge/bin/Release/*.nupkg"
  body: $(cat release_notes.md)
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
    - main

git:
  depth: 1

sudo: false
